### ISSUE TITLE
error in run_swatplus

### ISSUE THREAD

**Issue by Daveldw** [chrisschuerz/SWAT-R-Workshop#3]
Hi !
I met some an error when I ran these codes below:

q_out <- run_swatplus(project_path = proj_path, 
                      output = list(
                        flow = define_output(file = "channel",
                                             variable = "flo_out",
                                             unit = c(1, 3)),
                        et   = define_output(file = "basin_wb",
                                             variable = "et",
                                             unit = 1)))
Building 1 thread in 'D:/.../swatplus_rev60_demo/.model_run': 
 Completed 1 thread in 0S                                                   
Performing 1 simulation on 1 core: 
 Simulation 1 of 1   Time elapsed: 2S   Time remaining: 0S    Error in { : task 1 failed - "ℹ In index: 2.
Caused by error in `fread()`:
! File 'D:/.../swatplus_rev60_demo/.model_run/thread_1/channel_day.txt' does not exist or is non-readable. getwd()=='D:/...'"

I checked the folder ".model_run/thread_1/" and found that channel_day.txt didn't exist there.
I wonder what's the reason for that. Thank you so much!

**Comment by chrisschuerz** [comment]
The workshop materials refer to a much older version of SWAT+ where the output file was called channel. In newer versions of SWAT+ the file is called channel_sd, so you must define the outputs as follows: `define_output(file = "channel_sd", variable = "flo_out", unit = 1)`. Also I think in the new demo model setup there is only one channel, which I also corrected.

**Comment by Daveldw** [comment]
It worked! Thank u soooo much!

**Comment by chrisschuerz** [comment]
Sure, no problem. I generally suggest that you use the materials from here: https://chrisschuerz.github.io/SWATplusR/articles/SWATplusR.html as those are a bit more up to date.
